image: archlinux
sources:
  - https://git.sr.ht/~tcarrio/git-mirror
  - https://git.sr.ht/~tim-clifford/https-tim.clifford.lol
environment:
  GIT_TARGET_REPO: git@github.com:tim-clifford/https-tim.clifford.lol.git
secrets:
  - 9ee7c8f6-f330-46d7-8339-574c3d774548
tasks:
  - add-warning: |
      cd https-tim.clifford.lol
      git checkout master
      # fuck all this so much
      warning="

      | :exclamation:  | This is a mirror of [https://git.sr.ht/~tim-clifford/https-tim.clifford.lol](https://git.sr.ht/~tim-clifford/https-tim.clifford.lol). Please refrain from using GitHub's issue and PR system.  |
      |----------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------|

      "
      if test -f README.md; then
          echo "$warning" | cat - README.md > README2.md # save it, I literally do not care
      else
          echo "$warning" > README2.md
      fi
      # fuck all this redirection shit
      mv README2.md README.md
      git add README.md
      git commit -m "[builds.sr.ht] Add mirror warning to README.md"

  - mirror: git-mirror/git-mirror.sh https-tim.clifford.lol
